### PR TITLE
introduce skywalking-eye to check license header

### PR DESCRIPTION
**Pull request by dmsolr**

### CODE REVIEW

**Comment by dmsolr** [comment]
Hi @wu-sheng @moonming , I notice that all files under `./lib/resty` are missing license header. I am not sure whether those are required to add license header.

**Comment by wu-sheng** [comment]
> I notice that all files under ./lib/resty are missing license header

You could take a look at the LICENSE file, it is not written by us, so it is fine not having ASF header. We just copy them

**Comment by kezhenxu94** [comment]
> Hi @wu-sheng @moonming , I notice that all files under `./lib/resty` are missing license header. I am not sure whether those are required to add license header.

Files from 3rd-parties should be ignored in license-eyes

**Comment by dmsolr** [comment]
I got it. Thank both of you.

**Review by wu-sheng — APPROVED** [review]

**Pull request merged**
