### PR TITLE
Prepare for version 1.0.0 release and fix typos in doc.

### PR DESCRIPTION
**Pull request by wuwen5**

### CODE REVIEW

**Review by wu-sheng — APPROVED** [review]

**Comment by wu-sheng** [comment]
Could you prepare to write release doc?

**Comment by wuwen5** [comment]
I've drafted the release doc. Could you please confirm if it's aligned with your expectations ?

```
##  What's Changed
- Add IgnoreSuffix feature by @alonelaval in #93 
- CI run lua test cases with luajit by @tzssangglass in #94
- Feat support update the peer before requesting outgoing by @dmsolr in #95
- Use agent-test-tool docker image instead of building from source by @dmsolr in #96
- Support to try to use `request-id` as `trace-id` when trace context absent by @dmsolr in #104
- Stop reporting traces after the worker process begins to exit by @wangrzneu in #105
- Fix tag key from `http.status` to `http.status_code` by @wuwen5 in #107 

## New Contributors
- @alonelaval made their first contribution in #93
- @tzssangglass made their first contribution in #94
- @wuwen5 made their first contribution in #107

**Full Changelog**: https://github.com/apache/skywalking-nginx-lua/compare/v0.6.0...v1.0.0
```

**Comment by wu-sheng** [comment]
That chang logs are good. We need a doc to describe how to release, such as steps and relative shell commands.

**Comment by wu-sheng** [comment]
@wuwen5 Could you try https://luarocks.org/modules/apache-skywalking/skywalking-nginx-lua/1.0.0-0? Is that good?

**Comment by wuwen5** [comment]
@wu-sheng 
 I have conducted installation testing and it is good.
`luarocks install skywalking-nginx-lua 1.0.0-0`

**Comment by wu-sheng** [comment]
Thanks for the feedback.

**Pull request merged**
