### PR TITLE
ci: run lua test cases with luajit

### PR DESCRIPTION
**Pull request by tzssangglass**
since lua-cjson 2.1.0-1 may fail to install, ref
https://github.com/openresty/lua-cjson/issues/21, so use lua-cjson2,
ref: https://github.com/leafo/lapis/issues/539#issuecomment-319393395

Signed-off-by: tzssangglass <tzssangglass@gmail.com>

### CODE REVIEW

**Comment by wu-sheng** [comment]
Is this trying to help https://github.com/apache/skywalking-nginx-lua/pull/93?

**Comment by tzssangglass** [comment]
> Is this trying to help #93?

yes

**Comment by wu-sheng** [comment]
If you are going to change CI process, you need to change the doc here, https://github.com/apache/skywalking-nginx-lua#local-development-and-unit-tests

**Comment by tzssangglass** [comment]
> apache/skywalking-nginx-lua#local-development-and-unit-tests

Thanks for the reminder, I will change the doc after the CI pass.

**Comment by alonelaval** [comment]
great.

**Review by alonelaval — APPROVED** [review]

**Pull request merged**
