### PR TITLE
Updated tag key from `http.status` to `http.status_code`

### PR DESCRIPTION
**Pull request by wuwen5**
Updated tag key from `http.status` to `http.status_code` to ensure consistency with `searchableTracesTags`.

### CODE REVIEW

**Comment by wu-sheng** [comment]
Note, we don't have release manager for this agent for now.

**Comment by wu-sheng** [comment]
Please refer to the main repo, e2e tool should be updated.

**Comment by wu-sheng** [comment]
And CI VM env should be updated too. Otherwise, CI wouldn't run.

**Review by wu-sheng — APPROVED** [review]
If you are interested in joining us as a release manager, let me know.
I noticed you have made several commits in different repositories.

**Comment by wuwen5** [comment]
> If you are interested in joining us as a release manager, let me know. I noticed you have made several commits in different repositories.


@wu-sheng  Thank you for considering me for the release manager role. I'm indeed interested in joining the team and contributing my skills. Let me know what the next steps are.

**Comment by wu-sheng** [comment]
Ping me on slack. I could work with you to try for release.

**Pull request merged**
