### PR TITLE
rocks: fixed wrong version of luarocks.

### PR DESCRIPTION
**Pull request by moonming**

### CODE REVIEW

**Comment by wu-sheng** [comment]
Do we need this file for every version? Look like so. If yes,  do they have to be in the root?

**Comment by moonming** [comment]
This file can exist in any directory.

**Comment by wu-sheng** [comment]
What is the best practice for this file? Do we need to change it manually every time and add a new file? Do we have better way to do this?

**Comment by moonming** [comment]
> What is the best practice for this file? Do we need to change it manually every time and add a new file? Do we have better way to do this?

we can create a directory for these files, like https://github.com/apache/incubator-apisix/tree/master/rockspec.
yes, we need to change it manually every time and add a new file.

**Comment by wu-sheng** [comment]
OK. Let's create that folder too. And please update the release doc about this.

**Comment by wu-sheng** [comment]
@moonming Remember to fix this when you have time.

**Comment by moonming** [comment]
@wu-sheng  fixed, please take a look.

**Review by wu-sheng — APPROVED** [review]
Please upload to the luarocks.

**Pull request merged**
